### ISSUE TITLE
Wrath Classic Support

### ISSUE THREAD

**Issue by boktai1000** [darfink/ItemAutocomplete#7]
Hey there, left a comment on Curseforge but it felt like maybe opening up a GitHub Issue would be more applicable.

Just wanted to check in and see if there was any plans to update this for Wrath Classic and all the items that come with it. Cheers!

**Comment by NayooZ** [comment]
It is working for Wrath Classic already.

**Comment by zhavier042** [comment]
Incorrect, it has none of the new wrath items.

**Comment by maximus210793** [comment]
An WOTLK Classic update would be highly appreciated.
Thanks!

**Comment by boktai1000** [comment]
Please see the following pull request: https://github.com/darfink/ItemAutocomplete/pull/8

**Comment by darfink** [comment]
Updated with WOTLK items, thanks @boktai1000 🙏
